services:
  - type: web
    name: payfi-api
    runtime: node
    plan: starter
    buildCommand: npm ci && npx prisma generate --schema=apps/api/prisma/schema.prisma && npx turbo run build --filter=@payfi/api...
    startCommand: npx prisma db push --schema=apps/api/prisma/schema.prisma && node apps/api/dist/server.js
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SOMNIA_RPC_URL
        value: https://dream-rpc.somnia.network
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: ESCROW_ADDRESS
        value: "0x02916cDd952157156d17A255204462e40E90f129"
      - key: NFT_ADDRESS
        value: "0x065A50600376B537Ef5bE32cfc822a9DbCaD6399"
      - key: DEPLOY_BLOCK
        value: "398450593"
      - key: PORT
        value: "3001"
      - key: NODE_ENV
        value: production

  - type: web
    name: payfi-web
    runtime: node
    plan: starter
    buildCommand: npm ci && npx turbo run build --filter=@payfi/web...
    startCommand: cd apps/web && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://payfi-api.onrender.com
      - key: NEXT_PUBLIC_SOMNIA_RPC_URL
        value: https://dream-rpc.somnia.network
      - key: NEXT_PUBLIC_ESCROW_ADDRESS
        value: "0x02916cDd952157156d17A255204462e40E90f129"
      - key: NEXT_PUBLIC_NFT_ADDRESS
        value: "0x065A50600376B537Ef5bE32cfc822a9DbCaD6399"
      - key: NEXT_PUBLIC_CHAIN_ID
        value: "50312"
